### ISSUE TITLE
ListTransactions

### ISSUE THREAD

**Issue by old-mikser** [denpamusic/php-bitapi#51]
Fatal error: Uncaught Denpa\Bitcoin\Exceptions\BadRemoteCallException: Method not found in /var/www/html/bot/vendor/denpa/php-bitcoinrpc/src/Exceptions/Handler.php:70 Stack trace: #0 /var/www/html/bot/vendor/denpa/php-bitcoinrpc/src/Exceptions/Handler.php(107): Denpa\Bitcoin\Exceptions\Handler->requestExceptionHandler(Object(GuzzleHttp\Exception\ClientException)) #1 /var/www/html/bot/vendor/denpa/php-bitcoinrpc/src/Client.php(161): Denpa\Bitcoin\Exceptions\Handler->handle(Object(GuzzleHttp\Exception\ClientException)) #2 /var/www/html/bot/vendor/denpa/php-bitcoinrpc/src/Client.php(227): Denpa\Bitcoin\Client->request('listransactions') #3 /var/www/html/bot/index.php(19): Denpa\Bitcoin\Client->__call('listransactions', Array) #4 {main} thrown in /var/www/html/bot/vendor/denpa/php-bitcoinrpc/src/Exceptions/Handler.php on line 70

This is what I'm getting trying to run $bitcoind->listransactions();
Tried to use parameters like $bitcoind->listransactions('*',10); etc - got the same. 

You referred to https://bitcoin.org/en/developer-reference#bitcoin-core-apis in the description. Are there any other functions which are not working?

**Cryptocurrency**
* Software: Bitcoin Core v0.18.0
* Network: mainnet 

**Environment**
* PHP: 7.3
* Apache/2.4.18
* Ubuntu 16.04

**Comment by denpamusic** [comment]
Hi,
Every function is working fine, since this is simple client. You just have a typo in function name. It should be `listtransactions` (note double letter 't') instead of `listransactions` that you're trying to call. See function [description](https://bitcoin.org/en/developer-reference#listtransactions).

**Comment by denpamusic** [comment]
In order to avoid such typos in the future, I suggest, that you write method names in camel-case (i. e. `$bitcoind->listTransactions()`). It's a lot easier to spot typos this way.

**Comment by old-mikser** [comment]
Damn, I'm so embarrassed. I apologize for disturbing. 

Thanks for help!

**Comment by denpamusic** [comment]
No problem, it happens even to the best of us.
Glad that I've been able to help.
