### ISSUE TITLE
composer fails due to new Guzzle 7.0.1 with Laravel 7

### ISSUE THREAD

**Issue by michaelraasch** [denpamusic/php-bitapi#55]
**Describe the bug**
The latest Laravel version comes with Guzzle 7.0.1 See Guzzle 7 Released
Running composer fails with:
Your requirements could not be resolved to an installable set of packages.

**To Reproduce**
Run
composer require denpa/php-bitcoinrpc
with a fresh Laravel 7 installation

**Expected behavior**
Dependency should be met

**Logs**
composer require denpa/php-bitcoinrpc 
Using version ^2.1 for denpa/php-bitcoinrpc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0) -> satisfiable by guzzlehttp/guzzle[7.0.1].
    - denpa/php-bitcoinrpc 2.1.x-dev requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - denpa/php-bitcoinrpc 2.2.x-dev requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - denpa/php-bitcoinrpc v2.1.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - denpa/php-bitcoinrpc v2.1.1 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - denpa/php-bitcoinrpc v2.1.2 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for denpa/php-bitcoinrpc ^2.1 -> satisfiable by denpa/php-bitcoinrpc[2.1.x-dev, 2.2.x-dev, v2.1.0, v2.1.1, v2.1.2].

Installation failed, reverting ./composer.json to its original content.

**Environment**
Describe your runtime environment:

Laravel Framework 7.25.0
PHP 7.3.11 (cli) (built: Jun 5 2020 23:50:40) ( NTS )

**Comment by denpamusic** [comment]
Hi, sorry for late response and thanks for heads up!

I've bumped Guzzle to 7.0.* and released v2.1.3 of this package, [tests with Laravel 7 check out fine now](https://travis-ci.org/github/denpamusic/laravel-bitcoinrpc/builds/720329522).

This should hopefully fix your issue.

**Comment by michaelraasch** [comment]
Works. Thanks for the quick turnaround.
